In [5]:
import numpy as np

def get_user_input():
    # Prompt the user to input the number of interior grid points (N).
    N = int(input("Enter the number of interior grid points (N): "))
    if N < 1:
        raise ValueError("The number of interior points (N) must be a positive integer.")
    return N

def define_functions():
    # Define the functions A(x), B(x), and f(x) for the problem setup.
    A = lambda x: 0 * x # Function A(x) = 0
    B = lambda x: 0 * x # Function B(x) = 0
    f = lambda x: np.sin(np.pi * x) # f(x) = sin (pi x)
    return A, B, f

def compute_grid_points(N):
    # Compute the interior grid points excluding boundaries.
    return np.linspace(0, 1, N + 2)[1:-1] # Only interior points

def compute_diagonals(N, h, A, B, j):
    # Compute the main, super, and sub-diagonals for the tridiagonal matrix.
    main_diag = 2 / h**2 + B(j) # Main diagonal
    sup_diag = -1 / h**2 - A(j) / (2 * h) # Super diagonal
    sub_diag = -1 / h**2 + A(j) / (2 * h) # Sub diagonal
    return main_diag, sup_diag, sub_diag

def create_tridiagonal_matrix(main_diag, sup_diag, sub_diag):
    # Create the tridiagonal matrix.
    return np.diag(main_diag) + np.diag(sup_diag[:-1], 1) + np.diag(sub_diag[1:], -1)

def create_rhs_vector(f, j, sup_diag, sub_diag):
    # Create the right-hand side vector for the BVP.
    F = f(j)
    F[0] -= sub_diag[0] * 0 # Adjust for boundary at x = 0 (u(0) = 0)
    F[-1] -= sup_diag[-1] * 0 # Adjust for boundary at x = 1 (u(1) = 0)
    return F

def display_results(M, F):
    # Display the tridiagonal matrix and right-hand side vector.
    print("\n***\nOutput\n***\n")
    print("Tridiagonal Matrix M:\n")
    print(M)
    print("\nRight-Hand Side Vector F:\n")
    print(F)

def main():
    print("***\nUsing Finite Difference Methods to generate the tridiagonal matrix and right-hand side vector to approximate the BVP.\n***")
    
    try:
        # Step 1: Get user input
        N = get_user_input()
        
        # Step 2: Problem setup
        h = 1 / (N + 1) # Grid spacing
        
        # Step 3: Define the problem functions A(x), B(x), and f(x)
        A, B, f = define_functions()
        
        # Step 4: Compute grid points
        j = compute_grid_points(N)
        
        # Step 5: Compute diagonals
        main_diag, sup_diag, sub_diag = compute_diagonals(N, h, A, B, j)
        
        # Step 6: Create the tridiagonal matrix
        M = create_tridiagonal_matrix(main_diag, sup_diag, sub_diag)
        
        # Step 7: Create the right-hand side vector
        F = create_rhs_vector(f, j, sup_diag, sub_diag)
        
        # Step 8: Display the results
        display_results(M, F)
    
    except ValueError as e:
        print(f"Validation error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

# Run the main function
main()

***
Using Finite Difference Methods to generate the tridiagonal matrix and right-hand side vector to approximate the BVP.
***


Enter the number of interior grid points (N):  10



***
Output
***

Tridiagonal Matrix M:

[[ 242. -121.    0.    0.    0.    0.    0.    0.    0.    0.]
 [-121.  242. -121.    0.    0.    0.    0.    0.    0.    0.]
 [   0. -121.  242. -121.    0.    0.    0.    0.    0.    0.]
 [   0.    0. -121.  242. -121.    0.    0.    0.    0.    0.]
 [   0.    0.    0. -121.  242. -121.    0.    0.    0.    0.]
 [   0.    0.    0.    0. -121.  242. -121.    0.    0.    0.]
 [   0.    0.    0.    0.    0. -121.  242. -121.    0.    0.]
 [   0.    0.    0.    0.    0.    0. -121.  242. -121.    0.]
 [   0.    0.    0.    0.    0.    0.    0. -121.  242. -121.]
 [   0.    0.    0.    0.    0.    0.    0.    0. -121.  242.]]

Right-Hand Side Vector F:

[0.28173256 0.54064082 0.75574957 0.909632   0.98982144 0.98982144
 0.909632   0.75574957 0.54064082 0.28173256]
